# Generated by Django 4.0.4 on 2022-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_order_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
