# Generated by Django 4.0.4 on 2022-05-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_order_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='user',
        ),
    ]
